#!/usr/bin/env node

/*
Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

Copyright (c) 2016 Francesco Longo
*/

var a4t = require("./arduino4teachers-core-module");
var server = new a4t.server;
server.start();
